# Generated by Django 4.2.1 on 2023-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='jsondata',
            field=models.TextField(default={}),
        ),
    ]
